# Generated by Django 3.1.2 on 2020-10-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('peso', models.PositiveIntegerField()),
                ('dimension', models.PositiveIntegerField()),
                ('detalle', models.TextField(max_length=300)),
            ],
        ),
    ]
