# Generated by Django 3.1.2 on 2020-10-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagbase', '0002_auto_20201027_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.FileField(default=11, upload_to='fotos'),
            preserve_default=False,
        ),
    ]
