# Generated by Django 3.1.2 on 2020-11-26 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagbase', '0006_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
